Added test_cases for rest_api_flint.example endpoint
moja-global/FLINT.Cloud pull request #123
Opened 2022-05-30 18:46 UTC by AayushSaini101

Added test cases rest_api_flint.example endpoints

2022-05-31 06:29 UTC, HarshCasper requested changes
Please fix the failing test-cases here: https://github.com/moja-global/FLINT.Cloud/runs/6665368819?check_suite_focus=true

2022-06-04 07:06 UTC, HarshCasper requested changes

2022-06-04 07:06 UTC, HarshCasper commented on local/tests/test_rest_example.py
> +        assert help_all1_response.status_code== 200
Use better variable names.

2022-06-04 08:11 UTC, AayushSaini101 commented on local/tests/test_rest_example.py
> +        assert help_all1_response.status_code== 200
@HarshCasper  Done

2022-06-04 09:30 UTC, merged