Refactor readme
moja-global/FLINT.Cloud pull request #43
Opened 2021-12-27 15:31 UTC by Namyalg

## Description

The enhancements made : 
- Centered heading and introduction
- Added Table of Contents

## Type of change

- [X] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have checked my code and corrected any misspellings
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-12-27 17:06 UTC, HarshCasper requested changes
Few more changes: 

- Add technologies utilized in project development
- Like `CONTRIBUTING.md` and `LICENSE` aptly
- Change the API specs in a tabular format for easy analysis

2021-12-27 17:06 UTC, HarshCasper commented on README.md
> +<a href="#contributors"><img src="https://img.shields.io/badge/all_contributors-1-orange.svg?style=flat-square" /></a>
Remove this

2021-12-27 17:06 UTC, HarshCasper commented on README.md
> +<h1>FLINT.Cloud</h1>
Add the org logo: https://github.com/moja-global.png

2021-12-27 17:10 UTC, Namyalg commented
I will make the necessary changes.

2021-12-29 06:55 UTC, Namyalg commented
I have made the changes as mentioned @HarshCasper

2022-01-18 14:21 UTC, Namyalg commented
@HarshCasper , I have made the requested changes. Please let me know if there is anything I have to change

2022-02-21 16:33 UTC, closed without merging