fix the dockerfiles in the local directory
moja-global/FLINT.Cloud pull request #47
Opened 2022-01-06 13:59 UTC by asmijafar20

## Description

- Removed ENV PORT 
- Modified the CMD instruction in the `rest-api-gcbm` and `rest-api-flint.example` folders of the local directory. 
- The changes run the container successfully after building the image.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2022-01-06 18:33 UTC, HarshCasper requested changes
Why do I see @iamrajiv commits here? Did you do a proper rebase?

2022-01-06 23:48 UTC, iamrajiv commented
@HarshCasper Yeah like there was a problem in rebasing so I committed the changes.

2022-01-07 08:42 UTC, HarshCasper requested changes
There is an error here: https://github.com/moja-global/FLINT.Cloud/actions/runs/1663433375

Can you fix this?

2022-01-09 12:54 UTC, HarshCasper approved these changes

2022-01-09 12:54 UTC, merged