Add a CI for building and pushing docker image on GHCR.
moja-global/FLINT.Cloud pull request #51
Opened 2022-01-12 15:56 UTC by asmijafar20

## Description

- Added the `docker-ci.yml` workflow for building and pushing the docker image on the GitHub container registry using GitHub Actions. 
- The workflow runs when the release event triggers. 

@HarshCasper Please review it.

2022-01-15 05:13 UTC, iamrajiv commented
@asmijafar20 I have pulled to code and merged to my repository master branch [here](https://github.com/iamrajiv/FLINT.Cloud)to check whether the packages are publishing or not and I found it's not publishing.

2022-01-15 05:16 UTC, iamrajiv commented
@asmijafar20 I have pulled to code and merged to my repository master branch [here](https://github.com/iamrajiv/FLINT.Cloud) to check whether the packages are publishing or not and I found it's not publishing. Can you refer to this https://github.com/moja-global/FLINT.Example/pull/25?

2022-01-15 11:09 UTC, asmijafar20 commented
Just for checking

2022-01-15 11:12 UTC, asmijafar20 commented
checking

2022-01-15 11:36 UTC, asmijafar20 commented
> @asmijafar20 I have pulled to code and merged to my repository master branch [here](https://github.com/iamrajiv/FLINT.Cloud) to check whether the packages are publishing or not and I found it's not publishing. Can you refer to this [moja-global/FLINT.Example#25](https://github.com/moja-global/FLINT.Example/pull/25)?

Review it.

2022-01-16 04:16 UTC, HarshCasper requested changes
Can you update the file names as well? 

Change the filename of `ci.yml` to `docker-ci.yml` while changing the filename of `docker-ci.yml` to `docker-publish.yml`.

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +# This workflow uses actions that are not certified by GitHub.
Remove this comment

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +name: Create and publish a Docker image
Keep a meaningful name. Suggested: `Publish FLINT.Cloud images`

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +    branches: ["release"]
We would like the Docker images to be updated with every push. We don't have a "release" branch yet. Replace it with the "master" branch.

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +
Add Docker Buildx here.

```sh
       - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
```

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +          username: ${{ github.actor }}
Suggest change to `${{ github.repository_owner }}`. Refer docs here: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

2022-01-16 04:16 UTC, HarshCasper commented on .github/workflows/docker-ci.yml
> +          username: ${{ github.actor }}
Suggest change to ${{ github.repository_owner }}. Refer docs here: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

2022-01-17 10:12 UTC, merged